services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '3306:3306'
