# Generated by Django 2.2.13 on 2020-07-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Congregacion',
            fields=[
                ('id_congregacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_congregacion', models.CharField(max_length=45)),
                ('congregacion_direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'congregacion',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_fijo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'referencia',
            },
        ),
        migrations.CreateModel(
            name='TipoFamiliar',
            fields=[
                ('id_tipo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_familiar',
            },
        ),
        migrations.CreateModel(
            name='TipoReligion',
            fields=[
                ('id_tipo_religion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_religion',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=45)),
                ('telefono_movil', models.CharField(blank=True, max_length=45, null=True)),
                ('id_congregacion', models.ForeignKey(db_column='id_congregacion', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Congregacion')),
                ('id_estado_civil', models.ForeignKey(db_column='id_estado_civil', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.EstadoCivil')),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Localidad')),
                ('id_referencia', models.ForeignKey(db_column='id_referencia', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Referencia')),
            ],
            options={
                'unique_together': {('id_paciente', 'id_localidad', 'id_congregacion', 'id_estado_civil', 'id_referencia')},
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id_educacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Paciente')),
            ],
            options={
                'unique_together': {('id_educacion', 'id_paciente')},
                'db_table': 'educacion',
            },
        ),
        migrations.AddField(
            model_name='congregacion',
            name='id_tipo_religion',
            field=models.ForeignKey(db_column='id_tipo_religion', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.TipoReligion'),
        ),
        migrations.CreateModel(
            name='TratamientoAnterior',
            fields=[
                ('id_tratamiento_anterior', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('periodo', models.CharField(blank=True, max_length=45, null=True)),
                ('dado_alta', models.IntegerField()),
                ('alta_por_que_no', models.CharField(blank=True, max_length=255, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Paciente')),
            ],
            options={
                'unique_together': {('id_tratamiento_anterior', 'id_paciente')},
                'db_table': 'tratamiento_anterior',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=45)),
                ('hace_cuanto_trabajas_ahí', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Paciente')),
            ],
            options={
                'unique_together': {('id_trabajo', 'id_paciente')},
                'db_table': 'trabajo',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=45)),
                ('finalizado', models.BooleanField()),
                ('institucion', models.CharField(max_length=45)),
                ('id_educacion', models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Educacion')),
            ],
            options={
                'unique_together': {('id_grado', 'id_educacion')},
                'db_table': 'grado',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_movil', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('trato_con_ellos', models.TextField(blank=True, null=True)),
                ('vives_con_el', models.TextField(blank=True, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=45, null=True)),
                ('dui', models.CharField(blank=True, max_length=45, null=True)),
                ('responsable', models.IntegerField()),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Paciente')),
                ('id_tipo_familiar', models.ForeignKey(db_column='id_tipo_familiar', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.TipoFamiliar')),
            ],
            options={
                'unique_together': {('id_familiar', 'id_paciente', 'id_tipo_familiar')},
                'db_table': 'familiar',
            },
        ),
        migrations.CreateModel(
            name='EducacionSuperior',
            fields=[
                ('id_educacion_superior', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=45)),
                ('ciclo', models.CharField(max_length=45)),
                ('universidad', models.CharField(max_length=45)),
                ('finalizada', models.IntegerField()),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Carrera')),
                ('id_educacion', models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Educacion')),
            ],
            options={
                'unique_together': {('id_educacion_superior', 'id_educacion', 'id_carrera')},
                'db_table': 'educacion_superior',
            },
        ),
        migrations.CreateModel(
            name='EducacionBasica',
            fields=[
                ('id_educacion_basica', models.AutoField(primary_key=True, serialize=False)),
                ('grado_escolar', models.CharField(max_length=45)),
                ('institucion', models.CharField(max_length=45)),
                ('id_educacion', models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Educacion')),
            ],
            options={
                'unique_together': {('id_educacion_basica', 'id_educacion')},
                'db_table': 'educacion_basica',
            },
        ),
        migrations.CreateModel(
            name='DatosClinicos',
            fields=[
                ('id_datos_clinicos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=45)),
                ('medicamento', models.CharField(max_length=45)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Paciente')),
            ],
            options={
                'unique_together': {('id_datos_clinicos', 'id_paciente')},
                'db_table': 'datos_clinicos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='congregacion',
            unique_together={('id_congregacion', 'id_tipo_religion')},
        ),
    ]
