# Generated by Django 2.2.13 on 2020-07-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=45)),
                ('departamento', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono_fijo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'localidad',
            },
        ),
    ]
