# Generated by Django 2.2.13 on 2020-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacionsuperior',
            name='finalizada',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='responsable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tratamientoanterior',
            name='dado_alta',
            field=models.BooleanField(),
        ),
    ]
