# Generated by Django 2.2.13 on 2020-07-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Congregacion',
            fields=[
                ('id_congregacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_congregacion', models.CharField(max_length=45)),
                ('congregacion_direccion', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'congregacion',
            },
        ),
        migrations.CreateModel(
            name='DatosClinicos',
            fields=[
                ('id_datos_clinicos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=45)),
                ('medicamento', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'datos_clinicos',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('telefono_movil', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('trato_con_ellos', models.TextField(blank=True, null=True)),
                ('vives_con_el', models.TextField(blank=True, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=45, null=True)),
                ('dui', models.CharField(blank=True, max_length=45, null=True)),
                ('responsable', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'familiar',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'referencia',
            },
        ),
        migrations.CreateModel(
            name='TipoFamiliar',
            fields=[
                ('id_tipo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'tipo_familiar',
            },
        ),
        migrations.CreateModel(
            name='TipoReligion',
            fields=[
                ('id_tipo_religion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'tipo_religion',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=45)),
                ('hace_cuanto_trabajas_ahí', models.CharField(max_length=45)),
                ('cargo', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'trabajo',
            },
        ),
        migrations.CreateModel(
            name='TratamientoAnterior',
            fields=[
                ('id_tratamiento_anterior', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('periodo', models.CharField(blank=True, max_length=45, null=True)),
                ('dado_alta', models.IntegerField()),
                ('alta_por_que_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tratamiento_anterior',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=45)),
                ('telefono_movil', models.CharField(blank=True, max_length=45, null=True)),
                ('id_congregacion', models.ForeignKey(db_column='id_congregacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Congregacion')),
                ('id_estado_civil', models.ForeignKey(db_column='id_estado_civil', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.EstadoCivil')),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Localidad')),
                ('id_referencia', models.ForeignKey(db_column='id_referencia', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_paciente.Referencia')),
            ],
            options={
                'managed': True,
                'db_table': 'paciente',
                'unique_together': {('id_paciente', 'id_localidad', 'id_congregacion', 'id_estado_civil', 'id_referencia')},
            },
        ),
    ]
