# Generated by Django 2.2.13 on 2020-07-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0002_carrera_congregacion_datosclinicos_estadocivil_familiar_paciente_referencia_tipofamiliar_tiporeligio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
    ]
