# Generated by Django 2.2.13 on 2020-07-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0003_auto_20200728_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False},
        ),
    ]
