# Generated by Django 2.2.13 on 2020-08-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0003_auto_20200809_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacion',
            name='id_tipo_religion',
            field=models.ForeignKey(db_column='id_tipo_religion', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.TipoReligion'),
        ),
        migrations.AlterField(
            model_name='datosclinicos',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='educacionbasica',
            name='id_educacion',
            field=models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Educacion'),
        ),
        migrations.AlterField(
            model_name='educacionsuperior',
            name='id_carrera',
            field=models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Carrera'),
        ),
        migrations.AlterField(
            model_name='educacionsuperior',
            name='id_educacion',
            field=models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Educacion'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_tipo_familiar',
            field=models.ForeignKey(db_column='id_tipo_familiar', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.TipoFamiliar'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='id_educacion',
            field=models.ForeignKey(db_column='id_educacion', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Educacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_congregacion',
            field=models.ForeignKey(db_column='id_congregacion', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Congregacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_estado_civil',
            field=models.ForeignKey(db_column='id_estado_civil', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_localidad',
            field=models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Localidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_referencia',
            field=models.ForeignKey(db_column='id_referencia', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Referencia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_sexo',
            field=models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Sexo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='tratamientoanterior',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='registro_paciente.Paciente'),
        ),
    ]
