# Generated by Django 2.2.13 on 2020-07-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0004_auto_20200728_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': True},
        ),
    ]
