# Generated by Django 2.2.13 on 2020-07-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0005_auto_20200728_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': False},
        ),
    ]
