# Generated by Django 2.2.13 on 2020-07-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paciente', '0006_auto_20200728_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregacion',
            options={'managed': False},
        ),
    ]
